export const PERSISTENCE_ENGINES = {
  PRISMA: 'prisma',
  POSTGRES: 'postgres',
  SQLITE: 'sqlite',
} as const;

export const VALID_PERSISTENCE_ENGINES = Object.values(PERSISTENCE_ENGINES);

export const TRANSACTION_ISOLATION_LEVELS = {
  READ_UNCOMMITTED: 'READ UNCOMMITTED',
  READ_COMMITTED: 'READ COMMITTED',
  REPEATABLE_READ: 'REPEATABLE READ',
  SERIALIZABLE: 'SERIALIZABLE',
} as const;
