import type { StructureResolver } from 'sanity/structure'
import {
  HomeIcon,
  TagIcon,
  WrenchIcon,
  CogIcon,
  EnvelopeIcon,
  BlockElementIcon,
  ThListIcon,
  ComponentIcon,
  UserIcon,
} from '@sanity/icons'

export const structure: StructureResolver = (S) =>
  S.list()
    .title('RootGrain Studio')
    .items([
      S.listItem()
        .title('Content')
        .icon(HomeIcon)
        .child(
          S.list()
            .title('Content')
            .items([
              S.listItem()
                .title('Homepage')
                .id('homepage')
                .icon(HomeIcon)
                .child(
                  S.document()
                    .schemaType('homepage')
                    .documentId('homepage')
                ),
              S.documentTypeListItem('testimonial').title('Testimonials').icon(UserIcon),
            ])
        ),
      S.listItem()
        .title('Catalog')
        .icon(ThListIcon)
        .child(
          S.list()
            .title('Catalog')
            .items([
              S.documentTypeListItem('product').title('Products').icon(BlockElementIcon),
              S.documentTypeListItem('categoryGroup').title('Collections').icon(ThListIcon),
              S.documentTypeListItem('category').title('Categories').icon(TagIcon),
            ])
        ),
      S.listItem()
        .title('Workshop')
        .icon(WrenchIcon)
        .child(
          S.list()
            .title('Workshop')
            .items([
              S.documentTypeListItem('workshop').title('Workshop'),
              S.documentTypeListItem('craftsmanshipStep').title('Craftsmanship').icon(ComponentIcon),
            ])
        ),
      S.listItem()
        .title('Marketing')
        .icon(EnvelopeIcon)
        .child(
          S.list()
            .title('Marketing')
            .items([
              S.documentTypeListItem('subscriber').title('Subscribers').icon(EnvelopeIcon),
            ])
        ),
      S.divider(),
      S.listItem()
        .title('Settings')
        .icon(CogIcon)
        .child(
          S.list()
            .title('Settings')
            .items([
              S.listItem()
                .title('Site Settings')
                .id('siteSettings')
                .icon(CogIcon)
                .child(
                  S.document()
                    .schemaType('siteSettings')
                    .documentId('siteSettings')
                ),
            ])
        ),
    ])
