import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero Section' },
    { name: 'philosophy', title: 'Philosophy & Stats' },
    { name: 'lifestyle', title: 'Lifestyle & Collection' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline',
      type: 'styledText',
      group: 'hero',
      description: 'The main headline shown at the top of the homepage.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroSubheadline',
      title: 'Hero Subheadline',
      type: 'styledText',
      group: 'hero',
      description: 'The secondary text supporting the headline.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      group: 'hero',
      options: { hotspot: true },
      description: 'Background image for the hero section. Ensure it provides good contrast for the text.',
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroVideo',
      title: 'Hero Video (Optional)',
      type: 'mux.video',
      group: 'hero',
      description: 'Optional video for the hero section. The Hero Image is used as the poster fallback.',
    }),
    defineField({
      name: 'philosophyText',
      title: 'Philosophy Text',
      type: 'array',
      group: 'philosophy',
      of: [{ type: 'block' }],
      description: 'The narrative text explaining RootGrain’s philosophy.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'statsItems',
      title: 'Stats Items',
      type: 'array',
      group: 'philosophy',
      description: 'Key statistics to display (e.g., "10+" "Years of Experience").',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'number', type: 'string', title: 'Number', validation: (Rule) => Rule.required() },
            { name: 'label', type: 'string', title: 'Label', validation: (Rule) => Rule.required() },
          ],
        },
      ],
      validation: (Rule) => Rule.max(4).warning('We recommend a maximum of 4 stats for optimal design.'),
    }),
    defineField({
      name: 'philosophyEyebrow',
      title: 'Philosophy Eyebrow',
      type: 'string',
      group: 'philosophy',
      description: 'Optional eyebrow text above the philosophy title (e.g., "Our Materials").',
    }),
    defineField({
      name: 'philosophyTitle',
      title: 'Philosophy Title',
      type: 'string',
      group: 'philosophy',
      description: 'Optional title for the philosophy section (e.g., "Material Philosophy").',
    }),
    defineField({
      name: 'philosophyImage',
      title: 'Philosophy Image',
      type: 'image',
      group: 'philosophy',
      options: { hotspot: true },
      description: 'Optional image for the philosophy section. Falls back to default wood grain.',
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text' }],
    }),
    defineField({
      name: 'philosophyCtaLabel',
      title: 'Philosophy CTA Label',
      type: 'string',
      group: 'philosophy',
      description: 'Optional label for the Call to Action button (e.g., "Learn About Our Woods").',
    }),
    defineField({
      name: 'philosophyCtaUrl',
      title: 'Philosophy CTA URL',
      type: 'string',
      group: 'philosophy',
      description: 'Optional URL for the Call to Action button. If empty, the CTA will not be rendered.',
    }),
    defineField({
      name: 'featuredCollectionTitle',
      title: 'Featured Collection Title',
      type: 'string',
      group: 'lifestyle',
      description: 'Title for the featured products section (e.g., "Curated Collection").',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleTitle',
      title: 'Lifestyle Title',
      type: 'string',
      group: 'lifestyle',
      description: 'Title for the lifestyle imagery section.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleDescription',
      title: 'Lifestyle Description',
      type: 'text',
      group: 'lifestyle',
      rows: 3,
      description: 'Short description accompanying the lifestyle image.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleImage',
      title: 'Lifestyle Image',
      type: 'image',
      group: 'lifestyle',
      options: { hotspot: true },
      description: 'An inspiring image showing the furniture in a real space.',
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleVideo',
      title: 'Lifestyle Video (Optional)',
      type: 'mux.video',
      group: 'lifestyle',
      description: 'Optional video showing the furniture in a real space. The Lifestyle Image is used as the poster fallback.',
    }),
    defineField({
      name: 'lifestyleSpace',
      title: 'Lifestyle Space Label',
      type: 'string',
      group: 'lifestyle',
      description: 'e.g., "A Japandi Dining Room". Displayed near the lifestyle image.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleCtaLabel',
      title: 'Lifestyle CTA Label',
      type: 'string',
      group: 'lifestyle',
      description: 'Optional label for the lifestyle CTA button. Defaults to "Explore Spaces".',
      initialValue: 'Explore Spaces',
    }),
    defineField({
      name: 'lifestyleCtaUrl',
      title: 'Lifestyle CTA URL',
      type: 'string',
      group: 'lifestyle',
      description: 'Optional valid internal or external destination URL (e.g. "/collection" or "/#house-and-home"). Do not prefill with a fake route. If left empty, the button acts as non-navigational.',
    }),
    defineField({
      name: 'lifestyleCards',
      title: 'Lifestyle Cards',
      type: 'array',
      group: 'lifestyle',
      description: 'The two small cards displayed below the main Lifestyle content.',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'image',
              title: 'Image',
              type: 'image',
              options: { hotspot: true },
              fields: [
                {
                  name: 'alt',
                  type: 'string',
                  title: 'Alternative text',
                  validation: (Rule) => Rule.required().error('Alt text is required.'),
                },
              ],
              validation: (Rule) => Rule.required(),
            },
            {
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (Rule) => Rule.required(),
            },
            {
              name: 'subtitle',
              title: 'Subtitle',
              type: 'string',
              validation: (Rule) => Rule.required(),
            },
          ],
        },
      ],
      validation: (Rule) => Rule.max(2),
    }),
    defineField({
      name: 'seo',
      title: 'Search Engine Optimization',
      type: 'seo',
      group: 'seo',
    }),
  ],
})
