import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero Section' },
    { name: 'philosophy', title: 'Philosophy & Stats' },
    { name: 'lifestyle', title: 'Lifestyle & Collection' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline',
      type: 'styledText',
      group: 'hero',
      description: 'The main headline shown at the top of the homepage.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroSubheadline',
      title: 'Hero Subheadline',
      type: 'styledText',
      group: 'hero',
      description: 'The secondary text supporting the headline.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      group: 'hero',
      options: { hotspot: true },
      description: 'Background image for the hero section. Ensure it provides good contrast for the text.',
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'philosophyText',
      title: 'Philosophy Text',
      type: 'array',
      group: 'philosophy',
      of: [{ type: 'block' }],
      description: 'The narrative text explaining RootGrain’s philosophy.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'statsItems',
      title: 'Stats Items',
      type: 'array',
      group: 'philosophy',
      description: 'Key statistics to display (e.g., "10+" "Years of Experience").',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'number', type: 'string', title: 'Number', validation: (Rule) => Rule.required() },
            { name: 'label', type: 'string', title: 'Label', validation: (Rule) => Rule.required() },
          ],
        },
      ],
      validation: (Rule) => Rule.max(4).warning('We recommend a maximum of 4 stats for optimal design.'),
    }),
    defineField({
      name: 'featuredCollectionTitle',
      title: 'Featured Collection Title',
      type: 'string',
      group: 'lifestyle',
      description: 'Title for the featured products section (e.g., "Curated Collection").',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleTitle',
      title: 'Lifestyle Title',
      type: 'string',
      group: 'lifestyle',
      description: 'Title for the lifestyle imagery section.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleDescription',
      title: 'Lifestyle Description',
      type: 'text',
      group: 'lifestyle',
      rows: 3,
      description: 'Short description accompanying the lifestyle image.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleImage',
      title: 'Lifestyle Image',
      type: 'image',
      group: 'lifestyle',
      options: { hotspot: true },
      description: 'An inspiring image showing the furniture in a real space.',
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'lifestyleSpace',
      title: 'Lifestyle Space Label',
      type: 'string',
      group: 'lifestyle',
      description: 'e.g., "A Japandi Dining Room". Displayed near the lifestyle image.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'seo',
      title: 'Search Engine Optimization',
      type: 'seo',
      group: 'seo',
    }),
  ],
})
