import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'general', title: 'General & SEO' },
    { name: 'branding', title: 'Branding & Logos' },
    { name: 'contact', title: 'Contact & Social' },
    { name: 'legal', title: 'Legal & Footer' },
  ],
  fieldsets: [
    { name: 'logos', title: 'Site Logos', options: { collapsible: true, collapsed: false } },
    { name: 'contactDetails', title: 'Contact Details', options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    defineField({
      name: 'siteTitle',
      title: 'Site Title',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'websiteUrl',
      title: 'Website URL',
      type: 'url',
      group: 'general',
      description: 'The primary URL of the website (e.g., https://rootgrain.bd)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'general',
      description: 'A short slogan or tagline.',
    }),
    defineField({
      name: 'description',
      title: 'Brand Description',
      type: 'text',
      group: 'general',
      description: 'A short description of the brand used in the footer.',
    }),
    defineField({
      name: 'seo',
      title: 'Global SEO Settings',
      type: 'seo',
      group: 'general',
      description: 'Fallback SEO metadata used if a specific page lacks its own.',
    }),
    defineField({
      name: 'logo',
      title: 'Site Logo (Light / Default)',
      type: 'image',
      group: 'branding',
      fieldset: 'logos',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
    }),
    defineField({
      name: 'logoDark',
      title: 'Site Logo (Dark Mode)',
      type: 'image',
      group: 'branding',
      fieldset: 'logos',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
    }),
    defineField({
      name: 'logoEmail',
      title: 'Email Logo (Print / Email)',
      type: 'image',
      group: 'branding',
      fieldset: 'logos',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
    }),
    defineField({
      name: 'logoSquare',
      title: 'Square Logo (Profile / Icons)',
      type: 'image',
      group: 'branding',
      fieldset: 'logos',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'image',
      group: 'branding',
      fieldset: 'logos',
      options: { hotspot: true },
    }),
    defineField({
      name: 'ogImage',
      title: 'Open Graph Image (Social Sharing)',
      type: 'image',
      group: 'general',
      description: 'Fallback image when sharing links on social media. Recommended aspect ratio 1200x630.',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alternative text', validation: (Rule) => Rule.required().error('Alt text is required.') }],
    }),
    defineField({
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      group: 'contact',
      fieldset: 'contactDetails',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'contact',
      fieldset: 'contactDetails',
    }),
    defineField({
      name: 'hours',
      title: 'Business Hours',
      type: 'string',
      group: 'contact',
      fieldset: 'contactDetails',
    }),
    defineField({
      name: 'address',
      title: 'Address',
      type: 'object',
      group: 'contact',
      fields: [
        { name: 'line1', type: 'string', title: 'Line 1' },
        { name: 'line2', type: 'string', title: 'Line 2' },
      ],
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Links',
      type: 'object',
      group: 'contact',
      fields: [
        { name: 'instagram', type: 'url', title: 'Instagram URL' },
        { name: 'facebook', type: 'url', title: 'Facebook URL' },
        { name: 'twitter', type: 'url', title: 'Twitter URL' },
        { name: 'youtube', type: 'url', title: 'YouTube URL' },
        { name: 'linkedin', type: 'url', title: 'LinkedIn URL' },
        { name: 'pinterest', type: 'url', title: 'Pinterest URL' },
      ],
    }),
    defineField({
      name: 'copyright',
      title: 'Copyright Text',
      type: 'string',
      group: 'legal',
    }),
    defineField({
      name: 'origin',
      title: 'Origin Text',
      type: 'string',
      group: 'legal',
    }),
  ],
})
